title: Retention Radar - Customer Churn Data Prep
description: >
  Portfolio project prepping customer and streaming-history data for churn modeling,
  including ingestion, cleaning, EDA and feature-engineering in Python and pandas.
baseurl: "/retention-radar"
url: "https://marcin-charzynski.github.io"
include:
  - notebooks
plugins:
  - jekyll-remote-theme
  - jekyll-jupyter-notebook
remote_theme: Marcin-Charzynski/marcin-charzynski.github.io
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter_opts:
    line_numbers: true